version: '3'

services:
  node:
    container_name: markdownapp
    restart: always
    build: .
    ports:
      - '5000:5000'
    links:
      - mongo
  mongo:
    container_name: mongodatabase
    image: mongo
    ports:
      - '27018:27017'
